### ISSUE TITLE
Segmentation Fault on Ubuntu 15.10

### ISSUE THREAD

**Issue by zauberparacelsus** [InWorldz/whip-server#2]
A segmentation fault occurs when I try to run whip on Ubuntu 15.10 with boost 1.58 (Ubuntu does not have packages for 1.55).

GDB gives the following backtrace:
```#0  0x00000000006d8e72 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queueboost::asio::detail::task_io_service_operation&) ()
#1  0x00000000006d98a5 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lockboost::asio::detail::posix_mutex&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) ()
#2  0x00000000006d96c3 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
#3  0x00000000006d9b4c in boost::asio::io_service::run() ()
#4  0x00000000006e95bf in PushReplicationService::run() ()
#5  0x00000000006f24f5 in boost::_mfi::mf0<void, PushReplicationService>::operator()(PushReplicationService*) const ()
#6  0x00000000006f20b6 in void boost::_bi::list1boost::_bi::value<PushReplicationService* >::operator()<boost::_mfi::mf0<void, PushReplicationService>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, PushReplicationService>&, boost::_bi::list0&, int) ()
#7  0x00000000006f1b1a in boost::_bi::bind_t<void, boost::_mfi::mf0<void, PushReplicationService>, boost::_bi::list1boost::_bi::value<PushReplicationService* > >::operator()() ()
#8  0x00000000006f27ca in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, PushReplicationService>, boost::_bi::list1boost::_bi::value<PushReplicationService* > > >::run() ()
#9  0x00007ffff79a5bc5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#10 0x00007ffff7bc26aa in start_thread (arg=0x7ffff5a82700) at pthread_create.c:333
#11 0x00007ffff6592e9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109```

**Comment by linkedinyou** [comment]
bugs in POSIX that need fixing

**Comment by kf6kjg** [comment]
Is that on launch or during some operation?  I'm starting to explore WHIP on Ubuntu, and I'm compiling boost 1.55 from sources for the task.

**Comment by zauberparacelsus** [comment]
From what I recall, it was during launch.

**Comment by kf6kjg** [comment]
Ok, you should get a clean compile and execute with PR #4 and following the instructions at https://github.com/InWorldz/whip-server/wiki/Building-(Ubuntu)

I worked out the above under 16.04.1.
